language: java
jdk:
  - openjdk10
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
  - unzip -qq apache-maven-3.5.4-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.4
  - export PATH=$M2_HOME/bin:$PATH
install:
  - sh -c 'mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-example && mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-boot-example && mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-flyway-example && mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-guice-example && mvn install -DskipTests=true'
script:
  - sh -c 'mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-example && mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-boot-example && mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-flyway-example && mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-guice-example && mvn test'
cache:
  directories:
    - $HOME/.m2/repository
