language: java
jdk:
  - oraclejdk8
  - oraclejdk7
install: 
  - sh -c 'mvn install -DskipTests=true'
  - sh -c 'echo $JAVA_HOME | grep -q 8 && cd jOOQ-examples/jOOQ-spring-example && mvn install -DskipTests=true' || echo "Skipping for JDK6 and 7"
  - sh -c 'cd jOOQ-examples/jOOQ-spring-guice-example && mvn install -DskipTests=true'
  - sh -c 'echo $JAVA_HOME | grep -q 8 && cd jOOQ-test-utils && mvn install -DskipTest=true' || echo "Skipping for JDK6 and 7"
  - sh -c 'echo $JAVA_HOME | grep -q 8 && cd jOOQ-test && mvn install -DskipTests=true' || echo "Skipping for JDK6 and 7"
script: 
  - sh -c 'mvn test'
  - sh -c 'echo $JAVA_HOME | grep -q 8 && cd jOOQ-examples/jOOQ-spring-example && mvn test' || echo "Skipping for JDK6 and 7"
  - sh -c 'cd jOOQ-examples/jOOQ-spring-guice-example && mvn test'
  - sh -c 'echo $JAVA_HOME | grep -q 8 && cd jOOQ-test && mvn test -Dorg.jooq.test-dialects=h2 -Dorg.jooq.test.pretty-printer=false -Dlog4j.configuration=log4j-quiet.xml' || echo "Skipping for JDK6 and 7"
